import type { SlideMeta } from "../types";
import Slide01SmokeScene from "./Slide02SmokeScene";
import Slide02Cover from "./Slide01Cover";
import Slide03Problem from "./Slide03Problem";
import Slide04ImageGeneration from "./Slide04ImageGeneration";
import Slide05Diffusion from "./Slide05Diffusion";
import Slide06SoundSpeech from "./Slide06SoundSpeech";
import Slide07Fourier from "./Slide07Fourier";
import Slide08ControlStability from "./Slide08ControlStability";
import Slide09Probability from "./Slide09Probability";
import Slide10Conclusion from "./Slide10Conclusion";
import Slide11ThankYou from "./Slide11ThankYou";

/**
 * 11-slide deck — Engineering Mathematics applied to AI.
 *
 * Slide 1:  AI-Generated Scene (Gemini image)
 * Slide 2:  Cover — University, Title, Team, Faculty
 * Member 1 (3–5):  The Problem · AI Image Generation · Diffusion Models
 * Member 2 (6–7):  AI for Sound & Speech · Fourier Transform
 * Member 3 (8):    AI Control & Stability (Laplace Transform)
 *   Member 4 (9–11): Probability in AI · Conclusion · Thank You
 */
export const slideRegistry: SlideMeta[] = [
  // ===== Slide 1 — AI-Generated Scene =====
  {
    id: 1,
    title: "AI-Generated Scene",
    notes: [
      "This image was generated by Gemini AI.",
      "Shows Mr Tagor and Mr Ajmine taking cigarettes.",
      "Health tip: Cigarettes is injurious to health.",
    ],
    Component: Slide01SmokeScene,
  },
  // ===== Slide 2 — Cover =====
  {
    id: 2,
    title: "Applications of Engineering Mathematics in AI",
    notes: [
      "Welcome the audience. Topic: Applications of Engineering Mathematics in CSE.",
      "4-member team presenting how math powers AI.",
    ],
    Component: Slide02Cover,
  },
  // ===== Member 1 — The Problem through Diffusion =====
  {
    id: 3,
    title: "The Problem",
    notes: [
      "AI does things that seem intelligent — but a computer only processes numbers.",
      "How does AI generate images? How does it understand speech? How does it stay stable in real-time control?",
      "The answer: behind each feature is a mathematical equation. Our team will show how.",
    ],
    Component: Slide03Problem,
  },
  {
    id: 4,
    title: "AI Image Generation",
    notes: [
      "Member 1 continues. Tools like DALL·E and Stable Diffusion generate images from text.",
      "The math behind them is a differential equation solved in reverse — called a diffusion model.",
      "Explain the three steps: add noise to a real image, train a network to reverse the noise, then generate new images from pure noise.",
    ],
    Component: Slide04ImageGeneration,
  },
  {
    id: 5,
    title: "Diffusion Models",
    notes: [
      "Reveal the denoising equation: x_{t-1} = x_t - sigma_t * epsilon(x_t).",
      "At each step, the AI predicts the noise and subtracts it. Repeated many times, pure noise becomes a clear image.",
      "Watch the animation: the pixel grid denoises from random static into a cat. This is a differential equation running backwards.",
      "Hand off to Member 2: we now know how AI generates images. Next, how AI understands sound.",
    ],
    Component: Slide05Diffusion,
  },

  // ===== Member 2 — Fourier Transform =====
  {
    id: 6,
    title: "AI for Sound & Speech",
    notes: [
      "Member 2 takes over. Voice assistants like Siri and Alexa understand speech.",
      "The math behind them is the Fourier Transform — converting sound waves into frequencies.",
      "Explain the three steps: sound is a complex wave, the Fourier Transform splits it into pure frequencies, and AI matches frequency patterns to words.",
    ],
    Component: Slide06SoundSpeech,
  },
  {
    id: 7,
    title: "Fourier Transform",
    notes: [
      "Reveal the equation: F(omega) = integral of f(t) times e^{-i*omega*t} dt.",
      "The transform measures how much of each pure frequency is present in a sound wave — converting time to frequency.",
      "Watch the animation: the complex wave on top splits into individual frequency bars below. This is how AI hears.",
      "Hand off to Member 3: we now know how AI sees and hears. Next, how AI stays stable.",
    ],
    Component: Slide07Fourier,
  },

  // ===== Member 3 — Laplace Transform =====
  {
    id: 8,
    title: "AI Control & Stability",
    notes: [
      "Member 3 takes over. Self-driving cars and robotics need stable, real-time control.",
      "The Laplace Transform converts time-domain signals into the s-domain, where differential equations become simple algebra.",
      "Reveal the equation: F(s) = integral from 0 to infinity of f(t) times e^{-s*t} dt.",
      "In the s-domain, poles on the left half-plane mean a stable system — essential for reinforcement learning and autonomous control.",
      "Hand off to Member 4: we now have all three transforms. Next, the full picture.",
    ],
    Component: Slide08ControlStability,
  },

  // ===== Member 4 — Synthesis =====
  {
    id: 9,
    title: "Probability in AI",
    notes: [
      "Member 4 takes over. Topic: Probability in AI decision making.",
      "AI models output probabilities, not certainties.",
      "Example: image classifier predicts 95% cat, 5% dog.",
    ],
    Component: Slide09Probability,
  },
  {
    id: 10,
    title: "Conclusion",
    notes: [
      "Recap the journey: the problem, then Differential Equations, Fourier Transform, and Laplace Transform — together they power AI.",
      "The key message: Engineering Mathematics is not just theory — it is the engine of Artificial Intelligence.",
      "Every AI feature we use daily — image generators, voice assistants, self-driving cars — runs on mathematics.",
    ],
    Component: Slide10Conclusion,
  },
  {
    id: 11,
    title: "Thank You",
    notes: [
      "Thank the audience and the team.",
      "Invite questions.",
    ],
    Component: Slide11ThankYou,
  },
];
